### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [nibrunie/LZ17#2]
just this
```
 make test
./test_buffer
testing LZ17 without arithmetic coding
testing compression/decompression on an almost uniform 262144B buffer
compressed size is 228597 B
Makefile:32: set di istruzioni per l'obiettivo "test" non riuscito
make: *** [test] Errore di segmentazione (creato dump del core)
```

**Comment by nibrunie** [comment]
Indeed, I reproduced the bug on my setup, I will look into it. Sorry for the inconvenience.

**Comment by nibrunie** [comment]
I reverted the faulty commit on master, + added travis widget to show what is the status of the repo.

**Comment by Alessandro-Barbieri** [comment]
now `make test` works

**Comment by nibrunie** [comment]
Indeed, it was a two-sided issue
- tests were returning an error upon success
- the formation of a symbol for maximum back ref length was done improperly
