### ISSUE TITLE
Werror

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [nibrunie/LZ17#3]
Please don't release software with `-Werror` enabled by default, it doesn't help.

```
 make lz17utils
cc -Wall -Werror --pedantic -g -O0  -I../ArithmeticCoding/lib/ -Ilib utils/comp_util.c -o lz17utils liblz17.a ../ArithmeticCoding/libarithcoding.a
utils/comp_util.c: In function ‘main’:
utils/comp_util.c:30:8: error: unused variable ‘copt’ [-Werror=unused-variable]
   char copt;
        ^~~~
cc1: all warnings being treated as errors
Makefile:22: set di istruzioni per l'obiettivo "lz17utils" non riuscito
make: *** [lz17utils] Errore 1
```

**Comment by nibrunie** [comment]
Hello, 
    I am happy to receive any advice on my software, but please do not tell me how to write it. You are free to clone the repo, modify it, submit a pull request.I will have a look at this issue asap.

Regards,

**Comment by nibrunie** [comment]
I can modify the Makefile to allow customization of those options on the command line, but by default I would rather keep Werror. I am not going to ensure it works with every compiler version but IMHO it forces better code quality.

**Comment by Alessandro-Barbieri** [comment]
Some motivation to not use it outside development:
https://flameeyes.blog/2009/02/25/future-proof-your-code-dont-use-werror/amp/

https://embeddedartistry.com/blog/2017/5/3/-werror-is-not-your-friend?format=amp

https://news.ycombinator.com/item?id=12155223

**Comment by nibrunie** [comment]
Thank you for the references.
